Listing users in CSV and editing basic user profile properties.
ReCodEx/cli-old pull request #2
Opened 2018-04-27 12:26 UTC by krulis-martin

2018-05-31 13:11 UTC, janbuchar requested changes

2018-05-31 13:11 UTC, Teyras commented on recodex/plugins/users/cli.py
> +def edit(api: ApiClient, id, gravatar):
If I wanted to edit some other fields than gravatar url here, how would I do that?

2018-05-31 13:11 UTC, Teyras commented on recodex/plugins/users/cli.py
> +    return '"{}";"{}";"{}";"{}";"{}";"{}"'.format(
I would use the CSV writer from the standard library here. I know this is a trivial example, but it's possible we'll add more CSV exports that require it, and I would like to stay consistent here. Also, it would be nice if this CSV had a header.

2018-07-30 10:16 UTC, krulis-martin commented on recodex/plugins/users/cli.py
> +    return '"{}";"{}";"{}";"{}";"{}";"{}"'.format(
Will do.

2018-07-30 10:18 UTC, krulis-martin commented on recodex/plugins/users/cli.py
> +def edit(api: ApiClient, id, gravatar):
I thought that editing other parameters will be added on-demand. Since I had no divine all-covering solution, it might be better to augment this endpoint (adding new options) as we go.

2018-07-30 11:47 UTC, Teyras commented on recodex/plugins/users/cli.py
> +def edit(api: ApiClient, id, gravatar):
Speaking of divine solutions, how about opening a text editor with the JSON representation of the entity and letting the user modify it?

2018-07-30 11:49 UTC, krulis-martin commented on recodex/plugins/users/cli.py
> +def edit(api: ApiClient, id, gravatar):
:( I need a hug...

2018-07-30 11:49 UTC, krulis-martin commented on recodex/plugins/users/cli.py
> +def edit(api: ApiClient, id, gravatar):
...e stick to beat you with!

2018-07-30 14:13 UTC, janbuchar requested changes

2018-07-30 14:13 UTC, Teyras commented on recodex/api.py
> +        return self.get("/users/?filters[instanceId]={}&filters[search]={}".format(instance_id, search_string))["items"]
Cool!

2018-07-30 14:13 UTC, Teyras commented on recodex/api.py
> +        except Exception:
... How is this better than the original line?

2018-07-30 14:13 UTC, Teyras commented on recodex/plugins/users/cli.py
> +    click.echo("User {} ({} {}, {}) registered in instance {}".format(user_id, first_name, last_name, email, instance_id))
I would probably use named placeholders or f-strings here, the template is pretty hard to read.

2018-07-30 14:17 UTC, krulis-martin commented on recodex/api.py
> +        except Exception:
My linter was brooding over the previous line.

2018-07-30 14:18 UTC, krulis-martin commented on recodex/plugins/users/cli.py
> +    click.echo("User {} ({} {}, {}) registered in instance {}".format(user_id, first_name, last_name, email, instance_id))
Can do.

2018-07-30 14:49 UTC, janbuchar approved these changes

2018-07-30 15:01 UTC, merged